# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-slim

# Ensure Python output is sent straight to terminal (no buffering)
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Copy project files
COPY pyproject.toml poetry.lock README.md ./
COPY mcp_document_reader ./mcp_document_reader

# Install the MCP server
RUN pip install --upgrade pip \
    && pip install .

# Run over stdio by default
ENTRYPOINT ["mcp-document-reader"]
CMD []
